version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./dev.Dockerfile
    container_name: client
    tty: true
    command: npm run serve
    environment:
      - VUE_APP_API_URL=http://api:3030
    volumes:
      - ./client/src:/app/src
    ports:
      - 8080:8080
    depends_on:
      - api
  api:
    build: ./api
    container_name: api
    command: npm run serve
    volumes:
      - ./api/src:/app/src
      - ./api/public:/app/public
      - ./api/config:/app/config
    environment:
      - NODE_ENV=docker
    depends_on:
      - mongo
      - mongo-bi-connector
    ports:
      - 3030:3030
      - 1884:1883
  mongo:
    image: mongo:3.6
    container_name: mongo
    volumes:
       - mongodb-data:/data/db
    ports:
      - 27017:27017
    logging:
      driver: none
  mongo-bi-connector:
    image: 'codeanker/docker-mongo-bi-connector'
    ports:
      - 3307:3307
    command: wait-and-run.sh
    volumes:
      - ./shema.drdl:/etc/mongodb-bi-connector/schema/mongomysqlmap.drdl
    depends_on:
      - mongo
    environment:
      DB_NAME : mqtt-broker
      MONGO_HOST : mongo
      MONGO_PORT : 27017
      SCHEMA_PATH : /etc/mongodb-bi-connector/schema/mongomysqlmap.drdl
      ADDR : mongo-bi-connector:3307
    logging:
      driver: none

volumes:
  mongodb-data:
