version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./dev.Dockerfile
    tty: true
    command: npm run serve
    environment:
      - VUE_APP_API_URL=http://api:3030
    volumes:
      - ./client/src:/app/src
    ports:
      - 8080:8080
  api:
    build: ./api
    command: npm run serve
    volumes:
      - ./api/src:/app/src
      - ./api/public:/app/public
      - ./api/config:/app/config
    environment:
      - NODE_ENV=docker
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 1884:1883
  mongo:
    image: mongo:3.6
    volumes:
       - mongodb-data:/data/db
    ports:
      - 27017:27017
    logging:
      driver: none

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - client
  #     - api
  #   ports:
  #     - 8080:8080
  #     - 3031:3031
volumes:
  mongodb-data: