version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    tty: true
    depends_on:
      - api
    networks:
      mqtt-dashboard:
      pub:
        ipv4_address: 10.0.100.11
    restart: always
  api:
    build: ./api
    environment:
      - NODE_ENV=docker
    depends_on:
      - mongo
    networks:
      mqtt-dashboard:
      pub:
        ipv4_address: 10.0.100.10
    restart: always
  mongo:
    image: mongo:3.6
    volumes:
       - mongodb-data_prod:/data/db
    logging:
      driver: none
    networks:
      mqtt-dashboard:
    restart: always

volumes:
  mongodb-data_prod:

networks:
  mqtt-dashboard:
  pub:
    external: true
