name: Docker Image

on:
  push:
    branches:    
      - 'master'

jobs:
  build-api:
    name: Build Api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
    - name: Build the Docker image
      env:
        COMMIT: ${{ github.sha }}
      run: docker build ./api --file ./api/Dockerfile --tag supermomme/mqtt_api:${COMMIT}
    - name: Push Docker Image
      env:
        COMMIT: ${{ github.sha }}
      run: docker push supermomme/mqtt_api:${COMMIT}
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
    - name: Build the Docker image
      env:
        COMMIT: ${{ github.sha }}
      run: docker build ./client --file ./client/Dockerfile --tag supermomme/mqtt_client:${COMMIT}
    - name: Push Docker Image
      env:
        COMMIT: ${{ github.sha }}
      run: docker push supermomme/mqtt_client:${COMMIT}
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: [build-api, build-client]
    steps:
    - name: deploy api
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        COMMIT: ${{ github.sha }}
      with:
        args: set image --namespace mqtt-prod --record deployment/api api=supermomme/mqtt_api:${COMMIT}
    - name: deploy client
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        COMMIT: ${{ github.sha }}
      with:
        args: set image --namespace mqtt-prod --record deployment/client client=supermomme/mqtt_client:${COMMIT}
