name: Docker Image

on: [push]


jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - uses: actions/docker/login@master
    - name: Build the API Docker image
      run: docker build ./api --file ./api/Dockerfile --tag supermomme/mqtt_api:${GITHUB_SHA}
    - name: Push Docker Image
      run: docker push supermomme/mqtt_api:${GITHUB_SHA}
