name: Docker Image

on: [push]


jobs:

  build-api:
    name: Build Api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
    - name: Build the Docker image
      run: docker build ./api --file ./api/Dockerfile --tag supermomme/mqtt_api:${GITHUB_SHA} --tag supermomme/mqtt_api:master
    - name: Push Docker Image
      run: docker push supermomme/mqtt_api:${GITHUB_SHA}
    - name: Push Docker master Image if master
      if: github.ref == 'refs/heads/master'
      run: docker push supermomme/mqtt_api:master
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
    - name: Build the Docker image
      run: docker build ./client --file ./client/Dockerfile --tag supermomme/mqtt_client:${GITHUB_SHA} --tag supermomme/mqtt_client:master
    - name: Push Docker Image
      run: docker push supermomme/mqtt_client:${GITHUB_SHA}
    - name: Push Docker master Image if master
      if: github.ref == 'refs/heads/master'
      run: docker push supermomme/mqtt_client:master
  build-cubejs:
    name: Build CubeJS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
    - name: Build the Docker image
      run: docker build ./cubejs --file ./cubejs/Dockerfile --tag supermomme/mqtt_cubejs:${GITHUB_SHA} --tag supermomme/mqtt_cubejs:master
    - name: Push Docker Image
      run: docker push supermomme/mqtt_cubejs:${GITHUB_SHA}
    - name: Push Docker master Image if master
      if: github.ref == 'refs/heads/master'
      run: docker push supermomme/mqtt_cubejs:master
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: [build-api, build-client, build-cubejs]
    steps:
    - uses: actions/checkout@master
    - name: deploy api
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --namespace mqtt-prod --record deployment/api api=supermomme/mqtt_api:${{ github.sha }}
    
    # - name: verify deployment
    #   uses: steebchen/kubectl@master
    #   env:
    #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    #   with:
    #     args: '"rollout status deployment/my-app"'